/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as FamilyFamilyIdRouteImport } from './routes/family.$familyId'
import { Route as ItemFamilySlugRouteImport } from './routes/item.$family.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyFamilyIdRoute = FamilyFamilyIdRouteImport.update({
  id: '/family/$familyId',
  path: '/family/$familyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemFamilySlugRoute = ItemFamilySlugRouteImport.update({
  id: '/item/$family/$slug',
  path: '/item/$family/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/papers': typeof PapersRoute
  '/family/$familyId': typeof FamilyFamilyIdRoute
  '/item/$family/$slug': typeof ItemFamilySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/papers': typeof PapersRoute
  '/family/$familyId': typeof FamilyFamilyIdRoute
  '/item/$family/$slug': typeof ItemFamilySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/papers': typeof PapersRoute
  '/family/$familyId': typeof FamilyFamilyIdRoute
  '/item/$family/$slug': typeof ItemFamilySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/downloads' | '/papers' | '/family/$familyId' | '/item/$family/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/downloads' | '/papers' | '/family/$familyId' | '/item/$family/$slug'
  id:
    | '__root__'
    | '/'
    | '/downloads'
    | '/papers'
    | '/family/$familyId'
    | '/item/$family/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadsRoute: typeof DownloadsRoute
  PapersRoute: typeof PapersRoute
  FamilyFamilyIdRoute: typeof FamilyFamilyIdRoute
  ItemFamilySlugRoute: typeof ItemFamilySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/$familyId': {
      id: '/family/$familyId'
      path: '/family/$familyId'
      fullPath: '/family/$familyId'
      preLoaderRoute: typeof FamilyFamilyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$family/$slug': {
      id: '/item/$family/$slug'
      path: '/item/$family/$slug'
      fullPath: '/item/$family/$slug'
      preLoaderRoute: typeof ItemFamilySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadsRoute: DownloadsRoute,
  PapersRoute: PapersRoute,
  FamilyFamilyIdRoute: FamilyFamilyIdRoute,
  ItemFamilySlugRoute: ItemFamilySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
